### ISSUE TITLE
Add support for bulk permission editing

### ISSUE THREAD

**Issue by cfresh** [CrossLead/tyranid-gracl#22]
For the document methods which set/unset single permissions at a time, maybe accept arrays of permissions to set/unset?

**Comment by bsouthga** [comment]
added in https://github.com/CrossLead/tyranid-gracl/commit/c698bd6db7ac254daf9a7c873d3d7c959cafc77d you can now pass an array of permissions or a single permission (will only make one db call), for example

```javascript
await survey.$allow(['view', 'edit'], user);
```
