### ISSUE TITLE
Add perms to result set (optionally)

### ISSUE THREAD

**Issue by shindig** [CrossLead/tyranid-gracl#23]
Example as being done in controller code: https://github.com/CrossLead/crosslead-platform/blob/master/app/console/server/controllers/triangles.js#L3913

**Comment by bsouthga** [comment]
I emulated what you have with the concisely named document method: `doc.$determineAccessToAllPermissionsForResources(permList, uidList)`

You can see an example / usage here: http://crosslead.github.io/tyranid-gracl/globals.html#documentmethods
