### ISSUE TITLE
Can set undefined subjects

### ISSUE THREAD

**Issue by yangchristian** [CrossLead/tyranid-gracl#26]
In our main app, we are generating some permission docs w/invalid `uid`s:

```js
{
    "_id" : ObjectId("5730abc07103aab29b97f14d"),
    "resourceId" : "t015730abc058cc18340f7f3564",
    "subjectId" : "u00undefined",            // <-- Invalid uid
    "subjectType" : "user",
    "resourceType" : "someResourceType",
    "access" : {
        "own-someResourceType" : true
    }
}
```

I see that we have the following validation: https://github.com/CrossLead/tyranid-gracl/blob/abcbc67da00319c16a93d6047565af8c0ef27e20/lib/models/PermissionsModel.ts#L171

So seems like there is a validation bug somewhere, perhaps upstream.

**Comment by bsouthga** [comment]
added additional validation + tests here : https://github.com/CrossLead/tyranid-gracl/commit/400062c4ce2e42aa20cec954ec513b0ff50945e0
