### ISSUE TITLE
high level deny overriding low level allow in doc.$determineAccessToAllPermissionsForResources()

### ISSUE THREAD

**Issue by cfresh** [CrossLead/tyranid-gracl#27]
eg. 

- deny permission on organization resource

- allow permission on group resource

Should result in `true` for that permission checked against a user uid within the group, but returns false instead

**Comment by bsouthga** [comment]
additionally if there are conflicting denies + allows at the same parent level, the deny should win

**Comment by bsouthga** [comment]
fixed in `0.0.49`

**Comment by bsouthga** [comment]
This solution causes major performance issues -- need to find another way :/

**Comment by bsouthga** [comment]
fixed in `0.0.52`
